name: bay
channels:
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - python=3.5
  # scienctific computing
  - numpy=1.15.2
  - scipy=1.1.0
  - scikit-learn=0.20.0
  # visualization interactive ipython and notebook
  - matplotlib=3.0.0
  # data processing and management
  - pandas=0.23.4
  # for running R code in python
  - rpy2
  - pip:
    - tensorflow # tensorflow-gpu if you have gpu
    - tensorflow-probability
